# Generated by Django 3.2.16 on 2023-08-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20230824_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('In work', 'In Work'), ('Completed', 'Completed')], default='In work', max_length=30),
        ),
    ]
